### ISSUE TITLE
Crash in ngx_http_lua_io_read_all 

### ISSUE THREAD

**Issue by splitice** [tokers/lua-io-nginx-module#7]
```
#0  0x00005603b2e4b020 in ngx_http_lua_io_read_all ()
#1  0x00005603b2e4a3e7 in ngx_http_lua_io_file_do_read ()
#2  0x00005603b2e49fce in ngx_http_lua_io_prepare_retvals ()
#3  0x00005603b2e49672 in ngx_http_lua_io_resume ()
#4  0x00005603b2e49514 in ngx_http_lua_io_content_wev_handler ()
#5  0x00005603b2e495db in ngx_http_lua_io_thread_event_handler ()
#6  0x00005603b2c91d14 in ngx_thread_pool_handler ()
#7  0x00005603b2c8ff0b in ngx_epoll_notify_handler ()
#8  0x00005603b2c90a63 in ngx_epoll_process_events ()
#9  0x00005603b2c7f9c8 in ngx_process_events_and_timers ()
#10 0x00005603b2c8e362 in ngx_worker_process_cycle ()
#11 0x00005603b2c8ac63 in ngx_spawn_process ()
#12 0x00005603b2c8ddf1 in ngx_reap_children ()
#13 0x00005603b2c8cb39 in ngx_master_process_cycle ()
#14 0x00005603b2c4a7a5 in main ()
```

**Comment by splitice** [comment]
It looks like its related to #2

**Comment by splitice** [comment]
Basically when the lua context shuts down due to a timeout etc the file-io op is still executing and using lua memory.
